### update to example server
PUT http://localhost:4000/patients/cbb843e7-6262-4b82-a45e-a646d72fbba3
Content-Type: application/json

{
  "name": "Nishjhunt",
  "email": "rahul56189123@gmail.com",
  "address": "Bihar",
  "dateOfBirth": "2002-01-18",
  "registeredDate": "45-08-2003"

}

###